language: node_js
sudo: enabled
addons:
  apt:
    packages:
      - xvfb
install:
    - npm install -g tslint typescript tsd
    - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - npm test
